---
# 3.1.2 Ensure packet redirect sending is disabled (Scored)

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when: cis_hostonly
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  tags:
    - level1
    - section3
    - section3_level1
    - scored
    - "3.1.3"
