---
# 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)

- name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  tags:
    - level1
    - section3
    - section3_level1
    - scored
    - "3.2.5"
