---
# 3.4.1 Ensure TCP Wrappers is installed (Scored)

- name: 3.4.1 Ensure TCP Wrappers is installed (Scored)
  yum:
    name: tcp_wrappers
    state: present
  tags:
    - level1
    - level1_section3
    - section3
    - scored
    - "3.4.1"
