---
# 3.7 Ensure wireless interfaces are disabled (Not Scored)

- name: 3.7 Ensure wireless interfaces are disabled (Not Scored)
  debug:
    msg: "WARNING - This check has not been implemented yet."
  when: cis_firewall_default_policy == true
  tags:
    - level1
    - level1_section3
    - section3
    - "3.7"
