---
sudo: true
services: docker

env:
  - distro: centos7

before_install:
  # Pull container.
  - 'docker pull mauromedda/ansible:latest'
  
  # Get RepoName
  - 'repoName="$(basename `pwd`)"'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach mauromedda/ansible:latest test > "${container_id}"'

  # Run copy role to container
  - 'docker exec -t $(cat ${container_id}) bash -c "mkdir -p /srv/ansible/${repoName}"'
  - 'docker cp ./ $(cat ${container_id}):/srv/ansible/${repoName}'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" bash -c "cd /srv/ansible/${repoName}/tests && ansible-playbook test.yml --syntax-check"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
