---
# 1.1.11 Ensure separate partition exists for /var/log (Scored)
- name: 1.1.11 Ensure separate partition exists for /var/log (Scored)
  shell: mount | grep /dev
  register: var_mount
  changed_when: false
  check_mode: false
  tags:
    - section1
    - level2
    - section1_level2
    - "1.1.11"

- name: 1.1.11 Ensure separate partition exists for /var/log (Scored)
  debug: msg="***Manually create separete /var/log partition"
  when: "var_mount.stdout and '/var/log' not in var_mount.stdout"
  tags:
    - section1
    - level2
    - section1_level2
    - "1.1.11"

