---
# 1.1.6 Ensure separate partition exists for /var (Scored)

- name: 1.1.6 - Ensure separate partition exists for /var (Scored)
  shell: mount | grep /dev
  register: var_mount
  changed_when: false
  check_mode: false
  tags:
    - section1
    - level2
    - section1_level2
    - "1.1.6"

- name: 1.1.6 - Ensure separate partition exists for /var (Scored)
  debug: msg="***Manually create separete /var partition"
  when: "'/var' not in var_mount.stdout"
  tags:
    - section1
    - level2
    - section1_level2
    - "1.1.6"

