---
# 1.6.1.3 Ensure SELinux policy is configured (Scored)

- name: 1.6.1.3 Ensure SELinux policy is configured (Scored)
  selinux:
    conf: /etc/selinux/config
    policy: "{{ cis_selinux_policy }}"
    state: enforcing
  when: not cis_selinux_disabled
  tags:
    - level2
    - section1
    - section1_level2
    - scored
    - "1.6.1.3"
