---
# 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Not Scored)

- name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Not Scored)
  file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - section1
    - section1_level1
    - "1.7.1.6"
