---
# 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)

- name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - section1
    - section1_level1
    - "1.7.1.3"
