---
- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: autofs_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for xinetd service"
  shell: "systemctl show xinetd | grep LoadState | cut -d = -f 2"
  register: xinetd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check if chargen service is present"
  shell: chkconfig --list 2>/dev/null| grep chargen
  register: chargen_service_status
  changed_when: chargen_service_status.stdout and chargen_service_status.rc == 0
  failed_when: chargen_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if daytime service is present"
  shell: chkconfig --list 2>/dev/null| grep daytime
  register: daytime_service_status
  changed_when: daytime_service_status.stdout and daytime_service_status.rc == 0
  failed_when: daytime_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if discard service is present"
  shell: chkconfig --list 2>/dev/null| grep discard
  register: discard_service_status
  changed_when: discard_service_status.stdout and discard_service_status.rc == 0
  failed_when: discard_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if echo service is present"
  shell: chkconfig --list 2>/dev/null| grep echo
  register: echo_service_status
  changed_when: echo_service_status.stdout and echo_service_status.rc == 0
  failed_when: echo_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if time service is present"
  shell: chkconfig --list 2>/dev/null| grep time
  register: time_service_status
  changed_when: time_service_status.stdout and time_service_status.rc == 0
  failed_when: time_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if tftp server is present"
  shell: chkconfig --list 2>/dev/null| grep tftp
  register: tftp_service_status
  changed_when: tftp_service_status.stdout and tftp_service_status.rc == 0
  failed_when: tftp_service_status.rc not in (0, 1)
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for ntpd service"
  shell: "systemctl show ntpd | grep LoadState | cut -d = -f 2"
  register: ntpd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for chronyd service"
  shell: "systemctl show chronyd | grep LoadState | cut -d = -f 2"
  register: chronyd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true


- name: "PRELIM | Check for avahi-daemon service"
  shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for cups service"
  shell: "systemctl show cups | grep LoadState | cut -d = -f 2"
  register: cups_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for dhcpd service"
  shell: "systemctl show dhcpd | grep LoadState | cut -d = -f 2"
  register: dhcpd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for slapd service"
  shell: "systemctl show slapd | grep LoadState | cut -d = -f 2"
  register: slapd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for nfs service"
  shell: "systemctl show nfs | grep LoadState | cut -d = -f 2"
  register: nfs_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for rpcbind service"
  shell: "systemctl show rpcbind | grep LoadState | cut -d = -f 2"
  register: rpcbind_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for named service"
  shell: "systemctl show named | grep LoadState | cut -d = -f 2"
  register: named_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for vsftpd service"
  shell: "systemctl show vsftpd | grep LoadState | cut -d = -f 2"
  register: vsftpd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for httpd service"
  shell: "systemctl show httpd | grep LoadState | cut -d = -f 2"
  register: httpd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for dovecot service"
  shell: "systemctl show dovecot | grep LoadState | cut -d = -f 2"
  register: dovecot_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for smb service"
  shell: "systemctl show smb | grep LoadState | cut -d = -f 2"
  register: smb_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for squid service"
  shell: "systemctl show squid | grep LoadState | cut -d = -f 2"
  register: squid_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for snmpd service"
  shell: "systemctl show snmpd | grep LoadState | cut -d = -f 2"
  register: snmpd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for ypserv service"
  shell: "systemctl show ypserv | grep LoadState | cut -d = -f 2"
  register: ypserv_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for rsh.socket service"
  shell: "systemctl show rsh.socket | grep LoadState | cut -d = -f 2"
  register: rsh_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for rlogin.socket service"
  shell: "systemctl show rlogin.socket | grep LoadState | cut -d = -f 2"
  register: rlogin_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for rexec.socket service"
  shell: "systemctl show rexec.socket | grep LoadState | cut -d = -f 2"
  register: rexec_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for telnet service"
  shell: "systemctl show telnet | grep LoadState | cut -d = -f 2"
  register: telnet_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for rsyncd service"
  shell: "systemctl show rsyncd | grep LoadState | cut -d = -f 2"
  register: rsyncd_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check for ntalk service"
  shell: "systemctl show ntalk | grep LoadState | cut -d = -f 2"
  register: ntalk_service_status
  changed_when: no
  check_mode: no
  ignore_errors: true

- name: "PRELIM | Check if postfix package is installed"
  yum: list=postfix
  changed_when: no
  failed_when: no
  check_mode: no
  ignore_errors: true
  register: postfix_installed
  
