---
# conditional section01 tasks recommendations

- include: section01/1.1.1.1.yml
  when: "'1.1.1.1' not in cis_level_1_exclusions"

- include: section01/1.1.1.2.yml
  when: "'1.1.1.2' not in cis_level_1_exclusions"

- include: section01/1.1.1.3.yml
  when: "'1.1.1.3' not in cis_level_1_exclusions"

- include: section01/1.1.1.4.yml
  when: "'1.1.1.4' not in cis_level_1_exclusions"

- include: section01/1.1.1.5.yml
  when: "'1.1.1.5' not in cis_level_1_exclusions"

- include: section01/1.1.1.6.yml
  when: "'1.1.1.6' not in cis_level_1_exclusions"

- include: section01/1.1.1.7.yml
  when: "'1.1.1.7' not in cis_level_1_exclusions"

- include: section01/1.1.1.8.yml
  when: "'1.1.1.8' not in cis_level_1_exclusions"

- include: section01/1.1.2.yml
  when: "'1.1.2' not in cis_level_2_exclusions"

- include: section01/1.1.3.yml
  when: "'1.1.3' not in cis_level_1_exclusions and not cis_apply_level_2_profile"

