---
# conditional section3 tasks recommendations

- include: section3/3.1.1.yml
  when: "'3.1.1' not in cis_level_1_exclusions"

- include: section3/3.1.2.yml
  when: "'3.1.2' not in cis_level_1_exclusions"

- include: section3/3.2.1.yml
  when: "'3.2.1' not in cis_level_1_exclusions"

- include: section3/3.2.2.yml
  when: "'3.2.2' not in cis_level_1_exclusions"

- include: section3/3.2.3.yml
  when: "'3.2.3' not in cis_level_1_exclusions"

- include: section3/3.2.4.yml
  when: "'3.2.4' not in cis_level_1_exclusions"

- include: section3/3.2.5.yml
  when: "'3.2.5' not in cis_level_1_exclusions"

- include: section3/3.2.6.yml
  when: "'3.2.6' not in cis_level_1_exclusions"

- include: section3/3.2.7.yml
  when: "'3.2.7' not in cis_level_1_exclusions"

- include: section3/3.2.8.yml
  when: "'3.2.8' not in cis_level_1_exclusions"

- include: section3/3.3.1.yml
  when: "'3.3.1' not in cis_level_1_exclusions"

- include: section3/3.3.2.yml
  when: "'3.3.2' not in cis_level_1_exclusions"

- include: section3/3.3.3.yml
  when: "'3.3.3' not in cis_level_1_exclusions"

- include: section3/3.4.1.yml
  when: "'3.4.1' not in cis_level_1_exclusions"

- include: section3/3.4.2.yml
  when: "'3.4.2' not in cis_level_1_exclusions"

- include: section3/3.4.3.yml
  when: "'3.4.3' not in cis_level_1_exclusions"

- include: section3/3.4.4.yml
  when: "'3.4.4' not in cis_level_1_exclusions"

- include: section3/3.4.5.yml
  when: "'3.4.5' not in cis_level_1_exclusions"

- include: section3/3.5.1.yml
  when: "'3.5.1' not in cis_level_1_exclusions"

- include: section3/3.5.2.yml
  when: "'3.5.2' not in cis_level_1_exclusions"

- include: section3/3.5.3.yml
  when: "'3.5.3' not in cis_level_1_exclusions"

- include: section3/3.5.4.yml
  when: "'3.5.4' not in cis_level_1_exclusions"

