---
# handlers file for ansible_role_cis_centos

- name: restart tmp.mount
  become: yes
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: generate new grub config
  shell: grub2-mkconfig > /boot/grub2/grub.cfg

- name: update gdb
  shell: dconf update

- name: restart ntpd
  systemd:
    name: ntpd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: restart chronyd
  systemd:
    name: chronyd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    daemon_reload: yes
    enabled: yes
    state: restarted
