---
# 2.2.8 Ensure DNS Server is not enabled (Scored)

- name: 2.2.8 Ensure DNS Server is not enabled (Scored)
  systemd:
    name: named
    state: stopped
    enabled: no
  when: cis_named_server == false and named_service_status.stdout == "loaded"
  tags:
    - level1
    - section02
    - section02_level1
    - scored
    - "2.2.8"
