---
# 2.2.3 Ensure Avahi Server is not enabled (Scored)

- name: 2.2.3 Ensure Avahi Server is not enabled (Scored)
  systemd:
    name: avahi-daemon
    state: stopped
    enabled: no
  when: cis_avahi_server == false and avahi_service_status.stdout == "loaded"
  tags:
    - level1
    - section02
    - section02_level1
    - scored
    - "2.2.3"
