---
# 2.3.4 Ensure telnet client is not installed (Scored)

- name: 2.3.4 Ensure telnet client is not installed (Scored)
  yum:
    name: telnet
    state: absent
  when: cis_telnet_required == false
  tags:
    - level1
    - section02
    - section02_level1
    - scored
    - "2.3.4"
