---
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)

- name: 1.1.4 - Ensure nosuid option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nosuid']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level1
    - section01
    - section01_level1
    - "1.1.4"
    - scored
