---
# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
# 1.1.5 Ensure noexec option set on /tmp partition (Scored)

- name: 1.1.3 - Check if systemd tmp.mount unit-file exists
  stat:
    path: /etc/systemd/system/local-fs.target.wants/tmp.mount
  register: unitfile
  tags:
    - level1
    - section01_level1
    - section01
    - "1.1.3"
    - scored

- name: "1.1.3 - Ensure nodev option set on /tmp partition\n
         1.1.4 - Ensure nosuid option set on /tmp partition\n
         1.1.5 - Ensure noexec option set on /tmp partition\n
         | drop custom tmp.mount"
  lineinfile:
    dest: /etc/systemd/system/local-fs.target.wants/tmp.mount
    regexp: "^Options="
    insertafter: "^Type="
    line: "Options=mode=1777,strictatime,noexec,nodev,nosuid"
  when: unitfile.stat.exists
  tags:
    - level1
    - section01_level1
    - section01
    - "1.1.3"
    - scored
  notify: restart tmp.mount

