---
# 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)

- name: 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)
  yum:
    name: setroubleshoot
    state: absent
  tags:
    - level2
    - section01
    - section01_level2
    - scored
    - "1.6.1.4"
