---
# 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)

- name: 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)
  yum:
    name: mcstrans
    state: absent
  tags:
    - level2
    - section01
    - section01_level2
    - scored
    - "1.6.1.5"
