---
# 1.6.2 Ensure SELinux is installed (Scored)

- name: 1.6.2 Ensure SELinux is installed (Scored)
  yum:
    name: libselinux
    state: present
  when: not cis_selinux_disabled
  tags:
    - level2
    - section01
    - section01_level2
    - scored
    - "1.6.2"
