---
# 1.7.1.4 Ensure permissions on /etc/motd are configured (Not Scored)

- name: 1.7.1.4 Ensure permissions on /etc/motd are configured (Not Scored)
  file:
    path: /etc/motd
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - section01
    - section01_level1
    - "1.7.1.4"
